// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmoothieShop.Data;

#nullable disable

namespace SmoothieShop.Data.Migrations
{
    [DbContext(typeof(SmoothieShopDbContext))]
    partial class SmoothieShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("IngredientSmoothie", b =>
                {
                    b.Property<int>("IngredientsIngredientId")
                        .HasColumnType("int");

                    b.Property<int>("SmoothiesSmoothieId")
                        .HasColumnType("int");

                    b.HasKey("IngredientsIngredientId", "SmoothiesSmoothieId");

                    b.HasIndex("SmoothiesSmoothieId");

                    b.ToTable("IngredientSmoothie");
                });

            modelBuilder.Entity("MenuOrder", b =>
                {
                    b.Property<int>("MenusMenuId")
                        .HasColumnType("int");

                    b.Property<int>("OrdersOrderId")
                        .HasColumnType("int");

                    b.HasKey("MenusMenuId", "OrdersOrderId");

                    b.HasIndex("OrdersOrderId");

                    b.ToTable("MenuOrder");
                });

            modelBuilder.Entity("MenuSmoothie", b =>
                {
                    b.Property<int>("MenusMenuId")
                        .HasColumnType("int");

                    b.Property<int>("SmoothiesSmoothieId")
                        .HasColumnType("int");

                    b.HasKey("MenusMenuId", "SmoothiesSmoothieId");

                    b.HasIndex("SmoothiesSmoothieId");

                    b.ToTable("MenuSmoothie");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OrderSmoothie", b =>
                {
                    b.Property<int>("OrdersOrderId")
                        .HasColumnType("int");

                    b.Property<int>("SmoothiesSmoothieId")
                        .HasColumnType("int");

                    b.HasKey("OrdersOrderId", "SmoothiesSmoothieId");

                    b.HasIndex("SmoothiesSmoothieId");

                    b.ToTable("OrderSmoothie");
                });

            modelBuilder.Entity("SmoothieShop.Data.Data.Entites.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin@admin.com",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a13d75b4-720d-4d60-9005-8baff9841251",
                            Email = "admin@admin.com",
                            EmailConfirmed = false,
                            FirstName = "Ivan",
                            LastName = "Ivanov",
                            LockoutEnabled = false,
                            NormalizedEmail = "admin@admin.com",
                            NormalizedUserName = "admin@admin.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEFHCIuAoea5RyWHcN1NLkpx6fbNvR4g5GYiRlGp5UrcF5VDhZC5eynotzCbAO8fghQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4a946958-befe-4bf8-a2c4-9a262b5daa13",
                            TwoFactorEnabled = false,
                            UserName = "admin@admin.com"
                        },
                        new
                        {
                            Id = "productUser@product.com",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "040026e9-b518-4df4-a209-99db80d7e173",
                            Email = "productUser@product.com",
                            EmailConfirmed = false,
                            FirstName = "Stoqn",
                            LastName = "Stoqnov",
                            LockoutEnabled = false,
                            NormalizedEmail = "productUser@product.com",
                            NormalizedUserName = "productUser@product.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEOuuag23Qa7Q+Slxi351zFAdlnbWeQpEDJevfnxFh3DbknFBUQqRTobITp8aywau1Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "85009476-af4c-4375-a24c-01fb5c73406b",
                            TwoFactorEnabled = false,
                            UserName = "productUser@product.com"
                        },
                        new
                        {
                            Id = "customerUser@customer.com",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0ee0f48e-5d40-4b7e-bad2-ba2730cd4e69",
                            Email = "customerUser@customer.com",
                            EmailConfirmed = false,
                            FirstName = "Yordan",
                            LastName = "Yordanov",
                            LockoutEnabled = false,
                            NormalizedEmail = "customerUser@customer.com",
                            NormalizedUserName = "customerUser@customer.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEL1rU6nymXURviA7/WtedCUE29z5mDHu4CIF+coS0W9EE6zpsn0qgtqTPhA0wfKM2A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a7b1f19f-1b44-4019-932d-83c4f975668a",
                            TwoFactorEnabled = false,
                            UserName = "customerUser@customer.com"
                        },
                        new
                        {
                            Id = "guest1@guest.com",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fb9454da-e01e-4ae8-b034-256d28f678c9",
                            Email = "guest1@guest.com",
                            EmailConfirmed = false,
                            FirstName = "Petar",
                            LastName = "Petrov",
                            LockoutEnabled = false,
                            NormalizedEmail = "guest1@guest.com",
                            NormalizedUserName = "guest1@guest.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEBAjlfXiC27Gws7jE733Nlf3Heo+0ouwrMNLqsyEzW5j2Hcn/45GT+8JGgboN9YC0w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f325b408-69cb-40ff-aea9-b9791233c0f8",
                            TwoFactorEnabled = false,
                            UserName = "guest1@guest.com"
                        },
                        new
                        {
                            Id = "guest2@guest.com",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3a99bef1-44d7-4024-8dc7-e78f31e2b76f",
                            Email = "guest2@guest.com",
                            EmailConfirmed = false,
                            FirstName = "Dimitar",
                            LastName = "Dimitrov",
                            LockoutEnabled = false,
                            NormalizedEmail = "guest2@guest.com",
                            NormalizedUserName = "guest2@guest.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEF2680EvaqqdUS+pBAvjttbGcsudtc9SHtyH0Aid0mHupAgyYmvubNIbwDJaDahJEQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "93e345e6-5862-4898-8a0e-3a6e5c5b826e",
                            TwoFactorEnabled = false,
                            UserName = "guest2@guest.com"
                        });
                });

            modelBuilder.Entity("SmoothieShop.Data.Data.Entites.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CustomerUserId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CustomerId");

                    b.HasIndex("CustomerUserId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "Bulgaria",
                            CustomerUserId = 1,
                            Email = "guest1@guest.com",
                            FirstName = "Petar",
                            LastName = "Petrov",
                            PhoneNumber = "0000000000"
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "Bulgaria",
                            CustomerUserId = 1,
                            Email = "guest2@guest.com",
                            FirstName = "Dimitar",
                            LastName = "Dimitrov",
                            PhoneNumber = "0000000000"
                        });
                });

            modelBuilder.Entity("SmoothieShop.Data.Data.Entites.CustomerUser", b =>
                {
                    b.Property<int>("CustomerUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerUserId"), 1L, 1);

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CustomerUserId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("CustomerUsers");

                    b.HasData(
                        new
                        {
                            CustomerUserId = 1,
                            ApplicationUserId = "customerUser@customer.com"
                        });
                });

            modelBuilder.Entity("SmoothieShop.Data.Data.Entites.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"), 1L, 1);

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.HasKey("FeedbackId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Feedbacks");

                    b.HasData(
                        new
                        {
                            FeedbackId = 1,
                            Comment = "That was great smoothie.",
                            CustomerId = 1,
                            Rating = 10
                        },
                        new
                        {
                            FeedbackId = 2,
                            Comment = "That was amazing smoothie.",
                            CustomerId = 2,
                            Rating = 10
                        });
                });

            modelBuilder.Entity("SmoothieShop.Data.Data.Entites.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"), 1L, 1);

                    b.Property<double>("Calories")
                        .HasColumnType("float");

                    b.Property<string>("IngredientInfo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            Calories = 105.0,
                            IngredientInfo = "Bananas are berries, not fruits.",
                            IngredientName = "Banana"
                        },
                        new
                        {
                            IngredientId = 2,
                            Calories = 42.0,
                            IngredientInfo = "Kiwis are a type of berry and are related to strawberries and raspberries.",
                            IngredientName = "Kiwi"
                        },
                        new
                        {
                            IngredientId = 3,
                            Calories = 32.0,
                            IngredientInfo = "Strawberries are not actually berries, but rather an accessory fruit.",
                            IngredientName = "Strawberry"
                        });
                });

            modelBuilder.Entity("SmoothieShop.Data.Data.Entites.IngredientSmoothie", b =>
                {
                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("SmoothieId")
                        .HasColumnType("int");

                    b.HasKey("IngredientId", "SmoothieId");

                    b.HasIndex("SmoothieId");

                    b.ToTable("IngredientSmoothies");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            SmoothieId = 1
                        },
                        new
                        {
                            IngredientId = 3,
                            SmoothieId = 2
                        });
                });

            modelBuilder.Entity("SmoothieShop.Data.Data.Entites.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuId"), 1L, 1);

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProductUserId")
                        .HasColumnType("int");

                    b.HasKey("MenuId");

                    b.HasIndex("ProductUserId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            MenuName = "Basic",
                            ProductUserId = 1
                        });
                });

            modelBuilder.Entity("SmoothieShop.Data.Data.Entites.MenuOrder", b =>
                {
                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("MenuId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("MenuOrders");

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            OrderId = 1
                        },
                        new
                        {
                            MenuId = 1,
                            OrderId = 2
                        });
                });

            modelBuilder.Entity("SmoothieShop.Data.Data.Entites.MenuSmoothie", b =>
                {
                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("SmoothieId")
                        .HasColumnType("int");

                    b.HasKey("MenuId", "SmoothieId");

                    b.HasIndex("SmoothieId");

                    b.ToTable("MenuSmoothies");

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            SmoothieId = 1
                        },
                        new
                        {
                            MenuId = 1,
                            SmoothieId = 2
                        });
                });

            modelBuilder.Entity("SmoothieShop.Data.Data.Entites.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"), 1L, 1);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = 1,
                            Date = new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 4.50m
                        },
                        new
                        {
                            OrderId = 2,
                            CustomerId = 2,
                            Date = new DateTime(2023, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 5.50m
                        });
                });

            modelBuilder.Entity("SmoothieShop.Data.Data.Entites.OrderSmoothie", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("SmoothieId")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "SmoothieId");

                    b.HasIndex("SmoothieId");

                    b.ToTable("OrderSmoothies");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            SmoothieId = 1
                        },
                        new
                        {
                            OrderId = 2,
                            SmoothieId = 2
                        });
                });

            modelBuilder.Entity("SmoothieShop.Data.Data.Entites.ProductUser", b =>
                {
                    b.Property<int>("ProductUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductUserId"), 1L, 1);

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductUserId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("ProductUsers");

                    b.HasData(
                        new
                        {
                            ProductUserId = 1,
                            ApplicationUserId = "productUser@product.com"
                        });
                });

            modelBuilder.Entity("SmoothieShop.Data.Data.Entites.Smoothie", b =>
                {
                    b.Property<int>("SmoothieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SmoothieId"), 1L, 1);

                    b.Property<double>("Calories")
                        .HasColumnType("float");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.Property<string>("SmoothieName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SmoothieId");

                    b.ToTable("Smoothies");

                    b.HasData(
                        new
                        {
                            SmoothieId = 1,
                            Calories = 210.0,
                            Price = 4.50m,
                            Size = 250.0,
                            SmoothieName = "Banana Smoothie"
                        },
                        new
                        {
                            SmoothieId = 2,
                            Calories = 480.0,
                            Price = 5.50m,
                            Size = 250.0,
                            SmoothieName = "Strawberry Smoothie"
                        });
                });

            modelBuilder.Entity("SmoothieShop.Data.Data.Entites.ApplicationRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.HasDiscriminator().HasValue("ApplicationRole");
                });

            modelBuilder.Entity("IngredientSmoothie", b =>
                {
                    b.HasOne("SmoothieShop.Data.Data.Entites.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsIngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmoothieShop.Data.Data.Entites.Smoothie", null)
                        .WithMany()
                        .HasForeignKey("SmoothiesSmoothieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MenuOrder", b =>
                {
                    b.HasOne("SmoothieShop.Data.Data.Entites.Menu", null)
                        .WithMany()
                        .HasForeignKey("MenusMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmoothieShop.Data.Data.Entites.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MenuSmoothie", b =>
                {
                    b.HasOne("SmoothieShop.Data.Data.Entites.Menu", null)
                        .WithMany()
                        .HasForeignKey("MenusMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmoothieShop.Data.Data.Entites.Smoothie", null)
                        .WithMany()
                        .HasForeignKey("SmoothiesSmoothieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SmoothieShop.Data.Data.Entites.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SmoothieShop.Data.Data.Entites.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmoothieShop.Data.Data.Entites.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SmoothieShop.Data.Data.Entites.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderSmoothie", b =>
                {
                    b.HasOne("SmoothieShop.Data.Data.Entites.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmoothieShop.Data.Data.Entites.Smoothie", null)
                        .WithMany()
                        .HasForeignKey("SmoothiesSmoothieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmoothieShop.Data.Data.Entites.Customer", b =>
                {
                    b.HasOne("SmoothieShop.Data.Data.Entites.CustomerUser", "CustomerUser")
                        .WithMany()
                        .HasForeignKey("CustomerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerUser");
                });

            modelBuilder.Entity("SmoothieShop.Data.Data.Entites.CustomerUser", b =>
                {
                    b.HasOne("SmoothieShop.Data.Data.Entites.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("SmoothieShop.Data.Data.Entites.Feedback", b =>
                {
                    b.HasOne("SmoothieShop.Data.Data.Entites.Customer", "Customer")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SmoothieShop.Data.Data.Entites.IngredientSmoothie", b =>
                {
                    b.HasOne("SmoothieShop.Data.Data.Entites.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmoothieShop.Data.Data.Entites.Smoothie", "Smoothie")
                        .WithMany()
                        .HasForeignKey("SmoothieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Smoothie");
                });

            modelBuilder.Entity("SmoothieShop.Data.Data.Entites.Menu", b =>
                {
                    b.HasOne("SmoothieShop.Data.Data.Entites.ProductUser", "ProductUser")
                        .WithMany()
                        .HasForeignKey("ProductUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductUser");
                });

            modelBuilder.Entity("SmoothieShop.Data.Data.Entites.MenuOrder", b =>
                {
                    b.HasOne("SmoothieShop.Data.Data.Entites.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmoothieShop.Data.Data.Entites.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SmoothieShop.Data.Data.Entites.MenuSmoothie", b =>
                {
                    b.HasOne("SmoothieShop.Data.Data.Entites.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmoothieShop.Data.Data.Entites.Smoothie", "Smoothie")
                        .WithMany()
                        .HasForeignKey("SmoothieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Smoothie");
                });

            modelBuilder.Entity("SmoothieShop.Data.Data.Entites.Order", b =>
                {
                    b.HasOne("SmoothieShop.Data.Data.Entites.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SmoothieShop.Data.Data.Entites.OrderSmoothie", b =>
                {
                    b.HasOne("SmoothieShop.Data.Data.Entites.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmoothieShop.Data.Data.Entites.Smoothie", "Smoothie")
                        .WithMany()
                        .HasForeignKey("SmoothieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Smoothie");
                });

            modelBuilder.Entity("SmoothieShop.Data.Data.Entites.ProductUser", b =>
                {
                    b.HasOne("SmoothieShop.Data.Data.Entites.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("SmoothieShop.Data.Data.Entites.Customer", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
